name: CI

on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened]

jobs:
  # -----------------------------------------------------------------------
  # QUALITY — static analysis, code style & unit tests on PHP 7.4
  #    Runs on: PR opened/updated → develop or master
  # -----------------------------------------------------------------------
  quality:
    if: github.ref_type != 'tag' && github.event.action != 'closed'
    uses: payplug/template-ci/.github/workflows/php-quality.yml@main
    with:
      php-version: '7.4'

  sonarcloud:
    if: always() && !failure() && !cancelled() && github.base_ref == 'develop'
    needs: [ quality ]
    uses: payplug/template-ci/.github/workflows/sonarcloud.yml@main
    with:
      project-name: 'github-payplug-payplug-payplug-plugin-mcp'
      src-folder: 'src/'
    secrets:
      sonar-orga: ${{ secrets.SONAR_ORGA }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}